name: Build APK Otomatis

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest
    steps:
      - name: Ambil Kode
        uses: actions/checkout@v4

      - name: Setup Java 17 untuk Android
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Flutter Stabil (Bebas Bug JNI)
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.5'
          channel: 'stable'

      - name: Setujui Semua Lisensi Android SDK
        run: |
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses || true

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Flet Stabil & Build APK
        env:
          PYTHONUTF8: 1
        run: |
          pip install --upgrade pip
          pip install "flet==0.24.1" requests
          flet build apk --yes --skip-flutter-doctor -v

      - name: Siapkan File APK untuk Didownload
        uses: actions/upload-artifact@v4
        with:
          name: YT_Manager_Mobile_APK
          path: build/apk/**/*.apk
