name: Build APK Otomatis

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest
    steps:
      - name: Ambil Kode
        uses: actions/checkout@v4

      - name: Install Paket Linux
        run: |
          sudo apt-get update
          sudo apt-get install -y clang cmake ninja-build pkg-config libgtk-3-dev liblzma-dev mesa-utils zip unzip

      - name: Setup Java 17 untuk Android
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Android SDK 34 & NDK
        run: |
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses || true
          $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "platforms;android-34" "build-tools;34.0.0" "ndk;25.1.8937393"

      - name: Setup Flutter 3.27.1 (Mendukung wakelock_plus 1.4.0)
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.1'
          channel: 'stable'

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Flet 0.25.2 & Build APK
        env:
          PYTHONUTF8: 1
          GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.jvmargs=-Xmx4096m"
        run: |
          pip install --upgrade pip
          pip install "flet==0.25.2" requests
          flet build apk -vv

      - name: Siapkan File APK untuk Didownload
        uses: actions/upload-artifact@v4
        with:
          name: YT_Manager_Mobile_APK
          path: build/apk/**/*.apk
