name: Build APK Otomatis

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest
    steps:
      - name: Ambil Kode
        uses: actions/checkout@v4

      - name: Install Paket Linux yang Diminta Flutter Doctor
        run: |
          sudo apt-get update
          sudo apt-get install -y clang cmake ninja-build pkg-config libgtk-3-dev liblzma-dev mesa-utils

      - name: Setup Java 17 untuk Android
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setujui Semua Lisensi Android SDK Otomatis
        run: |
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses || true

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Flet & Build APK
        env:
          PYTHONUTF8: 1
        run: |
          pip install --upgrade pip
          pip install flet flet-cli requests
          flet build apk --yes --no-rich-output --skip-flutter-doctor -v

      - name: Siapkan File APK untuk Didownload
        uses: actions/upload-artifact@v4
        with:
          name: YT_Manager_Mobile_APK
          path: build/apk/**/*.apk
